version: '2'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  seed:
    image: mongo
    volumes:
      - ./server/seed/:/tmp/seed/
    depends_on:
      - mongo
    command:
      'bash -c "mongoimport --drop --host mongo --type json --db=periodic_api --file /tmp/seed/elements.json --jsonArray"'

networks:
  default:
    external:
      name: nginx-proxy
